[package]
name = "tokio-evacuate"
version = "1.0.0"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]
edition = "2018"

[dependencies]
futures = "^0.1"
tokio-timer = "^0.2"

[dev-dependencies]
tokio-executor = "^0.1"
